remote_theme: mmistakes/minimal-mistakes 
title: Home
include: ["_pages"]


author:
  name: "Kaia Crisp"
  avatar: "https://upload.wikimedia.org/wikipedia/commons/8/86/Maltese_puppy.jpeg"
  bio: "just A Cute Dog"
